spring:
datasource:
generate-unique-name: false
name: tacocloud
h2:
    console:
      enabled: true
      path: /h2-console
      datasource:
    url: jdbc:h2:mem:tacocloud
    username: sa
    password: mypass